### ISSUE TITLE
How does this line import plugins?

### ISSUE THREAD

**Issue by sahinakkaya** [willothy/nvim-config#3]
Hi, I am really impressed by all the efforts you put in this config to make it blazingly fast with lots of plugins. Great work! I want to rewrite my config based on this. However, there is one thing I can't understand. How does the following line work? What does it actually import? Does it import `plugins` directory inside `lua`? But `plugins` directory doesn't have an `init.lua`. Shouldn't there be an `init.lua` for it to be imported?

https://github.com/willothy/nvim-config/blob/34c13d29c3aecda150e6ab7ece9075546843f4e0/init.lua#L26

**Comment by willothy** [comment]
No, lazy imports submodules directly. I believe this is mentioned in the lazy docs. Feel free to take snippets from here, but I would not recommend using the entire config. There is lots of random code in this repo, I will randomly break it sometimes, and won't support it as I say in the readme.

Glad you like it, thanks! My biggest recommendation for optimizing startup is to lazy-load by default and use cmds / keys to only load plugins when needed.

**Comment by sahinakkaya** [comment]
Thanks for the info. 

No, I won't use this config. I need to rewrite my config so I thought organizing my code like this might be good.

**Comment by willothy** [comment]
here's where it's mentioned in the lazy docs:

https://github.com/folke/lazy.nvim?tab=readme-ov-file#-structuring-your-plugins

**Comment by willothy** [comment]
Oh, also forgot to mention: you may get to a point where the bottleneck of your startup is lazy reading spec files. Moving everything into 3-5 files should speed this up significantly (that's what I've done in my "plugins" dir).

**Comment by sahinakkaya** [comment]
I hate having plugin information and its config being on different files and I hate having files with 1000s of lines. So I was doing `{ import = "plugins" }` and inside `plugins` dir I had different files for different plugins. Like:
```
-- ./lua/plugins/whichkey.lua

return { 
   "folke/whichkey.nvim", 
   event = "VeryLazy",
   config = function 
       ... 
   end 
}
```

But I think that is what you were trying to say in previous comment. I have 39 plugins for now and startup time is already 46ms. It would improve if I move them into 3-5 files right? Like you have done with `editor.lua`, `ui.lua`?

**Comment by sahinakkaya** [comment]
Also, I tried to steal mousescroll things for telescope from your config but they don't seem to have any effect. Do I need some specific terminal setting or terminal to make them work? Normal scrolling works in neovim but when I hover over telescope window, neither results nor preview area can be scrolled. It instead scrolls the buffer under telescope window.

**Comment by willothy** [comment]
> But I think that is what you were trying to say in previous comment. I have 39 plugins for now and startup time is already 46ms. It would improve if I move them into 3-5 files right? Like you have done with `editor.lua`, `ui.lua`?

Yes that would likely be faster. They shouldn't need to be 1000s of lines because you configs can be separate, but this config is ~14k loc, so... it happens.

Check the `lazy.nvim` section of `:Lazy profile` to see if this will actually have benefit though - at 46ms you likely have slowdowns elsewhere in your config. Loading lazy specs will probably only be the bottleneck in the 12-20ms range. This does depend on system specs and OS though, I don't know. Benchmark times in the readme are from a Ryzen 5800x + samsung 970evo ssd, running linux (for comparison).

> Also, I tried to steal mousescroll things for telescope from your config but they don't seem to have any effect. Do I need some specific terminal setting or terminal to make them work? Normal scrolling works in neovim but when I hover over telescope window, neither results nor preview area can be scrolled. It instead scrolls the buffer under telescope window.

Works fine for me. I use wezterm nightly, all settings are in `willothy.settings`. I don't know what specifically could cause that to not work. Maybe `:h mousemoveevent`?
