### ISSUE TITLE
Is there any way to send notification while recording a macro?

### ISSUE THREAD

**Issue by pwnwriter** [willothy/nvim-config#4]
Hey,  your configuration provided me with a lot of useful information, thank you very much.

I'm curious if it's possible to receive a notification when I start and stop recording a macro using `vim.notify`? I couldn't find any other methods to chat with you, so I created this issue. Apologies for any inconvenience caused.

**Comment by pwnwriter** [comment]
I apparently found a way to send notification using `autocmd` on `RecordingEnter` and `RecorginLeave`. 

Diff: [`pwnvim/commit/50a04d2dca38432afa9a2bd55eaa9f70b8b3a81c`](https://github.com/pwnwriter/pwnvim/commit/50a04d2dca38432afa9a2bd55eaa9f70b8b3a81c)

**Comment by willothy** [comment]
I use `NeoComposer.nvim`'s user autocmds. This is good to know though, thanks! Glad you've found my config useful :)

Also no worries about opening an issue here - I'm happy to discuss / answer questions, it's just PRs and bug reports that I will not support here.
